ports:
- port: 3306
  onOpen: ignore
- port: 8080
  onOpen: ignore
  visibility: public
- port: 8081
  onOpen: open-browser
  visibility: public

#mysql -e "show databases;"
tasks:
  - init: |
      touch /tmp/.mysql-lock 
      gp await-port 3306 && mysql < Reset.sql
      rm /tmp/.mysql-lock
    command: gp await-port 3306 && mysql saloon 

  - init: sleep 1 && while [ -f /tmp/.mysql-lock ]; do sleep 1; done;
      gp await-port 3306 && mvn clean compile && mvn spring-boot:run

  - init: gp await-port 8080 && cd /workspace/Saloon/src/main/java/br/gov/sp/fatec/saloon/view && npm install && npm audit fix
    command: npm run serve
  #- command: gp await-port 8081 && gp preview $(gp url 8081)  
image: gitpod/workspace-mysql
