ports:
- port: 8080
- port: 8081
  onOpen: open-browser

#mysql -e "show databases;"
tasks:
  - init: |
      touch /tmp/.mysql-lock /tmp/.compile-lock
      mysql < Reset.sql
      rm /tmp/.mysql-lock
    command: mysql saloon 
  - init: sleep 1 && while [ -f /tmp/.mysql-lock ]; do sleep 1; done;
      mvn clean compile;
      rm /tmp/.compile-lock;
    command: mvn spring-boot:run
  - init: sleep 1 && while [ -f /tmp/.compile-lock ]; do sleep 1; done;
      touch /tmp/.npm-lock;
      npm install;
      rm /tmp/.npm-lock;
image: gitpod/workspace-mysql
