ports:
- port: 8080
tasks:
  - init: |
      touch /tmp/.mysql-lock
      mysql < Reset.sql
      rm touch /tmp/.mysql-lock
      mvn clean package
    command: mvn spring-boot:run
image: gitpod/workspace-mysql
